document.write('	<div class="footer">')
document.write('	<div class="main_wrapper">')
	document.write('<div class="onerow">')
	document.write('<div class="col6">')
	document.write('<div class="ft_inner" style=" text-align:left!important;">')
	document.write('<p> <a href="http://ggim.un.org/" target="blank">About UN-GGIM</a> </p>')
	document.write('</div>')
	document.write('</div>')    
    document.write('<div class="col6 last">')
	document.write('<div class="ft_inner" style=" text-align:right!important;">')
	document.write('<p>Site managed by <a href="https://wgicouncil.org/?utm_source=unggim-psn.org&utm_medium=footer" target="blank">World Geospatial Industry Council (WGIC)</a> </p>')
	document.write('</div>')
	document.write('</div>')
	document.write('</div>')
	document.write('</div>')
	document.write('</div>')