document.write('<div class="header">')
document.write('<div class="navigation">')
document.write('<div class="main_wrapper">')
document.write('<div class="onerow">')
document.write('<div class="col12">')
document.write('<ul id="menu">')
document.write('<li><a href="index.html">HOME</a></li>')
document.write('<li><a href="JavaScript:Void(0)">ABOUT psn</a>')                       
document.write('<ul class="one">')
document.write('<li><a href="preamble.html">PREAMBLE</a></li>')
document.write('<li><a href="about.html#VISION">VISION</a></li>')
document.write('<li><a href="about.html#PURPOSE">PURPOSE </a></li>')
document.write('<li><a href="about.html#GUIDING">GUIDING PRINCIPLES</a></li>')
document.write('</ul>')                        
document.write('</li>')                                 
document.write('<li><a href="members.html">PSN BOARD </a></li>')
document.write('<li><a href="psn-members.html">PSN MEMBERS </a></li>')
document.write('<li><a href="MOM.html">MOM</a></li>')
document.write('<li><a href="reports.html">Documents</a></li>')
<!--document.write('<li><a href="psn-activities.html">PSN ACTIVITIES </a></li>')-->
//document.write('<li><a href="foundingmembers.html">FOUNDING MEMBERS </a></li>')
document.write('<li><a href="index.html#contact">CONTACT US</a></li>')
document.write('<li><a href="http://unggim-psn.org/submit-eoi.html?utm_source=06july2017&utm_medium=email&utm_campaign=Invitation" class="active">Be a Member</a></li>')
document.write('</ul>')
document.write('</div>')
document.write('</div>')
document.write('</div>')
document.write('</div>')
document.write('<div class="ms_top">')
document.write('<img src="images/logo-new-2.png" />')
document.write('</div>')
document.write('</div>')